- hosts: k8s_hard
  tags: host-defaults
  tasks:
  - ansible.builtin.import_role:
      name: host-defaults

- hosts: k8s_hard_jumpbox
  tags: jumpbox
  tasks:
  - ansible.builtin.import_role:
      name: jumpbox

- hosts: k8s_hard
  tags: compute-resources
  tasks:
  - ansible.builtin.import_role:
      name: compute-resources

- hosts: k8s_hard
  tags: certificate-authority
  tasks:
  - ansible.builtin.import_role:
      name: certificate-authority

- hosts: k8s_hard
  tags: kubernetes-config-files
  tasks:
  - ansible.builtin.import_role:
      name: kubernetes-config-files

- hosts: k8s_hard
  tags: data-encryption-keys
  tasks:
  - ansible.builtin.import_role:
      name: data-encryption-keys